// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zoknyeevtxvzwgdkubwq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpva255ZWV2dHh2endnZGt1YndxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4MzkyOTYsImV4cCI6MjA1NjQxNTI5Nn0.B4slIkRqomhS14b4cv0Kn9VF0jS6QOqwH8xNTiEqxJE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);